### ISSUE TITLE
Merge Schema types on GQL?

### ISSUE THREAD

**Issue by Morphexe** [graphql-compose/graphql-compose#107]
Is there anyway to merge Schemas defined in an other GraphQLSchema into GQL? I want to use types defined in another Schema on GQL, but whenever I try it says that the type does not exist.

Do you have any idea how to accomplish this?

**Comment by yoadsn** [comment]
In fact, I was trying something similar a few days ago.

I generated a schema using `graphql-tools` to check for something related to schema stitching.
I then wanted to manipulate that schema using GQLC but `TypeComposer` could not accept that schema or any type on that schema in the constructor.

When thinking about it a bit more I realized GQLC is the combination of schema and execution logic (in the form of the Resolver concept).

You GraphQLSchema had execution logic in the form of a simple 'resolve' attached to it - what did you expect to get when importing it to GQLC? A tree of `TypeComposer`? Resolvers? A populated type storage?
I wonder since we might want to build something like this ourselves.
(I hope i'm not talking nonesense here)

**Comment by Morphexe** [comment]
I was able to merge/stich the schemas using merge-tools, that works fine, I just want to be able to use the types across both definitions.

Let's say I have the Type ErrorMessage defined in error.graphql file.

using a TypeComposer, I want to be able to define a resolver that returns the type of ErrorMessage. but I can't seem to figure out a way to use the types defined outside oF GQC since it throws a error.

Currently I trying to figure out a way to get the types definitions from a GraphQLAst to generate TypeComposer from there, just so I am able to use the defined types in GQC.

I was glancing at the source of GQC, and I think the perfect solution would be to extract type information from the AST, so that when it makes the checks for the types it also checks the "imported types".

**Comment by nodkz** [comment]
I catch a great idea about adding some type to the store for further use it in type definitions. I've just add a new method `GQC.add()`, which accepts `TypeComposer` or `InputTypeComposer`. And make them usable in type definitions, eg. https://github.com/graphql-compose/graphql-compose/blob/c47c5c5414a07516b8ed009aaebebb0fdf428e82/src/__tests__/github_issues/107-test.js#L206-L226

Also, I added bunch of other cases of stitching some GraphQL Schema with graphql-compose schema, take a look https://github.com/graphql-compose/graphql-compose/blob/master/src/__tests__/github_issues/107-test.js

TypeMapper just added `parseTypesFromString()` and `parseTypesFromAst()` methods which return you a `TypeStorage` (a proxied `Map` object). It contains `GraphQLNamedType`s from your SDL. https://github.com/graphql-compose/graphql-compose/blob/22a37fe06a4f9a3be82dcb95b67e09a5e79ebb60/src/__tests__/typeMapper-test.js#L668-L690
So you may get only needed types and use them in your TC types.

So, today my additions cover all type of stitching from GraphQLSchema and SDL with granular tuning.

Need something else?

**Comment by yoadsn** [comment]
@nodkz Thanks a lot for this fix! you are the BEST - I went away and experimented with it.

My Goal:
Using `graphql-tools` (they have this functionality)
1. Take remote schema using introspection and generate client schema form it
2. Connect automatic resolves to pass any query on this schema to original API endpoint

I do this for example like this:
```
import { HttpLink } from 'apollo-link-http';
import { makeRemoteExecutableSchema, introspectSchema } from 'graphql-tools';
...
const link = new HttpLink({ uri: `${platformApiEntryURL}/graphql`, fetch });
const remoteSchema = await introspectSchema(link);
const schema = makeRemoteExecutableSchema({ schema: remoteSchema, link });
```
At this stage `schema` contains all the types from the remote api and it resolves by proxieing any query on that schema using http.

3. Pull out of this schema some type and it's resolves
4. Use this type inside my own GQLC schema and manipulate using TCs, Resolvers etc.

I tried this using the latest version and this code:
```
...
const rootQueryTC = TypeComposer.create(schema._queryType);
const UserTC = rootQueryTC.getFieldTC('user'); // Has type "User"
GQC.add(UserTC);
GQC.rootQuery().addFields({
  user: {
    type: 'User',
    resolve: UserTC.getType().resolve, // <am I crazy to try this?>
  }
});
```

It fails in multiple ways - first - when trying to introspect the result GQC schema (on the final client) I get the following error from graphiQL:
```
Error: Invalid or incomplete schema, unknown type: User. Ensure that a full introspection query is used in order to build a client schema.
```
It seems like adding the User type to GQC did not get what I wanted.

Additionally the `resolve` from the generated remote schema "proxy" disappears:
```
schema._queryType._fields.user.resolve // function exists
rootQueryTC.gqType._fields.user.resolve // function exists
rootQueryTC.getField('user').resolve // undefined
```
And this is probably due to the TC `_fields` inititialization [here](https://github.com/graphql-compose/graphql-compose/blob/39abaec6b8178d7db1220c04f1e5a0cee546c330/src/typeComposer.js#L219-L222):
```
    if (!this._fields) {
      const fields: Thunk<GraphQLFieldConfigMap<any, any>> = this.gqType._typeConfig.fields;
      this._fields = resolveMaybeThunk(fields) || {};
    }
``` 
Which uses the type configuration and not the actual fields.. I guess I should have expected that..

What do you think? Am I trying something crazy?

**Comment by nodkz** [comment]
> resolve: UserTC.getType().resolve, // <am I crazy to try this?>

Yep, you are crazy ;)
GraphQL Types do not contain `resolve` function. That's why you cannot get resolve function from Type.
Fields with FieldConfigs has resolve function:
```js
const usersFieldConfig = {
  type: UserType,
  resolve: () => { ... },
}
``` 
Cause you may use one Type in different ways how to get them and return (as one element, array or connection). 

If you want to get resolve function, you need to go upper on parent type, read some field and its FieldConfig. From this FC get a type and construct TypeComposer, and again from this FC get resolve function and put it as a Resolver to your constructed TypeComposer.

PS. It better to do it several times manually. Understand what exactly can be automated. And then write some helper for `graphql-compose` or even more write a new plugin for remote schemas.

PSS. graphql-compose-mongoose provides for you too much magic ))) with its built-in Resolvers. That why I thinking that TypeComposer better to call GraphQLModel ( type, + a bunch of methods for retrieving/modificating data in different ways for its type).

**Comment by yoadsn** [comment]
Oh yeah, now I fully understand.
I will hack around those remote schemas and see if I can start grasping how the "compose" family could have its own implementation of such ability.

`graphql-tools` approach is to attach at "build time" tree of resolve functions. So the model is the gql string and implementation is separate and in JS.

BTW - Also, another thing I loved they did was to use the "fragment" concept when they need to represent what we call "projection" - for example when we build a relation between types. This is natural for GQL concepts while "projection" is natural for us mongoDB people.
See how they use fragments [here](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html#adding-resolvers)

I agree that `graphql-compose-mongoose` is hiding this separation from new users of GQLC but Resolver concept is such a strong idea that I would keep it as a reusable abstraction for field configs wherever possible.

PS - The name "GraphQLModel" for me represents just the type system without implementation of resolver. I was thinking of some other ideas:
GraphQLTypeStrategy (like the Strategy design pattern)
GraphQLTypeExecutor
TypeResolutionComposer

But not sure any makes sense to others.

**Comment by Morphexe** [comment]
@nodkz  That's exactly what I need. Thank you !
