### ISSUE TITLE
`setTypeName` doesn't update the usage of the type?

### ISSUE THREAD

**Issue by dotansimha** [graphql-compose/graphql-compose#238]
Hi @nodkz :) 
I'm trying to use `graphql-compose` to rename all GraphQL types in a schema (and add a prefix to it), but it seems like `setTypeName` doesn't apply the changes to the actual usage in fields.

My code is:
```ts
  const typeMap = schema.getTypeMap();

  for (const [typeName, type] of Object.entries(typeMap)) {
    if (!typeName.startsWith('__')) {
      composer.get(type).setTypeName(`Test_${typeName}`);
    }
  }
``` 

But later, when I try to do `composer.buildSchema()`, I'm getting errors about non-existing types, and it seems like each fields are not being updated. 

Does `setTypeName` should update the usage of types with the new name? is that a bug or unrealistic expectations? :D

**Comment by dotansimha** [comment]
Ok nevermind, it seems like an issue that's not related directly to `graphql-compose` :)

**Comment by dotansimha** [comment]
Ok I found the actual issue, and it might be related to compose. 
It seems like `astNode` doesn't getting updated when dealing with `union` types.

So when changing a type name, where a union exists, something like:

```graphql
type A { a: String }
type B { b: String }
type U = A | B
```

Into new naming, let's say to prefix all types with `T_`, the actual result SDL is:

```graphql
type T_A { a: String }
type T_B { b: String }
type T_U = T_A | T_B
```

But, and, if I do that on the schema:

```
const myUnionType = schema.getType('T_U')
```

It will work, but then `astNode` seems to be off:

```
const types = myUnionType.getTypes() // types is `[T_A, T_B]`
const astTypes = myUnionType.astNode.types // types is `[A, B]`, which is not updated
```

**Comment by nodkz** [comment]
@dotansimha I added a test case for your issue and it really does not work with AstNodes
https://github.com/graphql-compose/graphql-compose/blob/db416443bb122ab39f07e372f93c252add1f2262/src/__tests__/github_issues/238-test.js#L74-L75

Firstly I just fix to use proper type names on astNode construction. But after that, I decide to make internal refactoring – now it keeps types in `Set` instead of `Map`. For ast was used keys from `Map` and these keys do not sync on types renaming. That's why you got the wrong Ast data.

Please try a new version 7.12.5

PS. If you'll meet with some other errors, feel free to open PR with broken tests like `238-test.js`. Thanks.

**Comment by dotansimha** [comment]
This is awesome! I can confirm that `7.12.5` works :) 
Thank you so much @nodkz
