### ISSUE TITLE
Object directives are removed from schema

### ISSUE THREAD

**Issue by craicoverflow** [graphql-compose/graphql-compose#273]
Directives are removed from the object when either `buildSchema` or `toSDL` are called.

```ts
const schema = buildSchema(
`directive @test on OBJECT

type ModifyMe @test {
  id: ID!
}

type Query {
  hello: ModifyMe
}`)

const schemaComposer = new SchemaComposer(schema);

const schemaStr = schemaComposer.toSDL({ exclude: ['ID', 'String', 'Int', 'Boolean', 'Float'] })

console.log(schemaStr)
```

This outputs:

```graphql
directive @test on OBJECT

"""Exposes a URL that specifies the behaviour of this scalar."""
directive @specifiedBy(
  """The URL that specifies the behaviour of this scalar."""
  url: String!
) on SCALAR

type TestObject {
  id: ID!
}

type Query {
  hello: TestObject
}
```

Note the missing `@test` directive on TestObject

**Comment by wtrocki** [comment]
Same happens to field definitions

**Comment by wtrocki** [comment]
Quick investigation shows that problem is in 

https://github.com/graphql-compose/graphql-compose/blob/master/src/utils/schemaPrinter.js#L423

This method bases on ast and it is missing directives (they shown as undefined).
So compose must be changing something as schema has this directive enabled:

`console.log(schema.getType("ModifyMe")?.astNode?.directives)`

**Comment by craicoverflow** [comment]
I think the problem is deeper than that @wtrocki. I was debugging this and the directives are lost from the type in memory.

See [ObjectTyoeComposer#getDirectives](https://github.com/graphql-compose/graphql-compose/blob/master/src/ObjectTypeComposer.js#L1547). Directives are being obtained through the type extensions property, which is undefined. Would it be better to obtain these through the astNode?

```patch
getDirectives(): Array<ExtensionsDirective> {
-  const directives = this.getExtension('directives');
+  const directives = this._gqType.astNode.directives;
  ...
}
```

**Comment by wtrocki** [comment]
Yes. Maybe we can fix it with unit test so we could release our own unofficial version till this land

**Comment by nodkz** [comment]
Thanks for reporting about this problem.

For your issue was create test case https://github.com/graphql-compose/graphql-compose/blob/master/src/__tests__/github_issues/273-test.js

Now all works correctly.

In the future feel free to open broken PR with failed test cases like above. It greatly helps me to save time & fastly resolve issues.

**Comment by nodkz** [comment]
@wtrocki you wrote
> Same happens to field definitions

If this another problem stays in 7.19.1, please open a new issue with a test case.
Thanks!

**Comment by machi1990** [comment]
@nodkz thanks for the fix!
