### ISSUE TITLE
Memoize type.getFields in ObjectTypeComposer.js?

### ISSUE THREAD

**Issue by KyleAMathews** [graphql-compose/graphql-compose#319]
I'm doing some profiling on Gatsby query running for a site & the hottest function is getting the fields for a type. I assume this could be memoized? It gets called 10s of thousands of times for a small-ish site.

<img width="553" alt="Screen Shot 2021-02-26 at 10 44 06 AM" src="https://user-images.githubusercontent.com/71047/109341802-c33ff500-781f-11eb-82ef-0af3b19d9113.png">

**Comment by nodkz** [comment]
Wow, it sounds very bad.

Let's try to investigate what's wrong. I start to add my thought in the free form here. Maybe we can found the root of the problem together.

## Step 1

`defineFieldMap()` is important method - it constructs the proper `astNode` property inside graphql type (so we cannot get rid of this method). This method is not expensive - it just traverses two times fields with all args for graphql type construction; does not have any recursions. 

So the problem somewhere higher - something calls this method many times.

## Step 2

If we take a look at simplified `ObjectTypeComposer.getType()` method implementation:
```js
  getType(): GraphQLObjectType { // <------------------------------------------------ POINT_0
    this._gqType.astNode = getObjectTypeDefinitionNode(this);
    this._gqType._fields = () => {
      return defineFieldMap( // <---------------------------------------------------- POINT_1
        this._gqType,
        mapEachKey(this._gqcFields, (fc, name) => this.getFieldConfig(name)),  // <-- POINT_2
        this._gqType.astNode
      );
    };
    this._gqType._interfaces = () => this.getInterfacesTypes();
    return this._gqType;
  }
```

- Somwhere we call `ObjectTypeComposer.getType()` (POINT_0) and it return wrapped in array function `defineFieldMap` call (POINT_1). And it will be resolved by `graphql-js` on schema construction.
- We can notice that before calling `defineFieldMap` (POINT_1) we call `getFieldConfig()` for every field (POINT_2).
- Under the hood `getFieldConfig()` (POINT_2) calls `ObjectTypeComposer.getType()` method (POINT_0). 💣💣💣 So here is recursion and `defineFieldMap` may be called several times for the one type (unnecessary excessive computations).

Definitely, we need to add memorization for `ObjectTypeComposer.getType()` method.

**Comment by nodkz** [comment]
Now is the good question: How we can add memorization to `ObjectTypeComposer.getType()` method? What properties can be used for tracking changes inside ObjectTypeComposer?

cc @vladar maybe you have any thoughts?

**Comment by KyleAMathews** [comment]
I think `getFields` is the main problem as it gets called over and over again by graphql-js & gatsby as you can see here:

<img width="727" alt="Screen Shot 2021-02-26 at 11 47 32 AM" src="https://user-images.githubusercontent.com/71047/109347962-c1c6fa80-7828-11eb-88d7-d2accac46d56.png">


`getFields` has ~5.3s of CPU time in my sample & `getType` has 0.4s — though that's also pretty expensive so probably both need memoized.

**Comment by KyleAMathews** [comment]
How do you change the type? Are they immutable? Or have easily trackable ways of mutation? If so, we could just always return the cached version right?

**Comment by KyleAMathews** [comment]
Or perhaps if it's not easy to tell when a type is mutated, perhaps we could manually "freeze" the types since we're controlling changing them.

**Comment by vladar** [comment]
For me this code path looks problematic:

https://github.com/graphql-compose/graphql-compose/blob/e8637117d162d94afd34a7d6ea186bffd0344d9a/src/ObjectTypeComposer.js#L965-L974

Anytime we call `composer.getType()` we basically reset `_fields` to the new thunk. Even if it was already initialized previously.

So `graphql-js` always re-runs it [here](https://github.com/graphql/graphql-js/blob/735975d4904c5d9cc93d0c0a02af181e8f02dfba/src/type/definition.js#L728-L733):

```js
  getFields(): GraphQLFieldMap<any, any> {
    if (typeof this._fields === 'function') {
      this._fields = this._fields();
    }
    return this._fields;
  }
```

So maybe if we skip this code path when `this._fields` is `object` (so was previously defined) - it should be enough? But I am not sure if it will interfere with something else (maybe there are cases when we _want_ to override previously defined fields).

**Comment by vladar** [comment]
Probably a bad idea - 53 tests are failing 😅

**Comment by vladar** [comment]
I am actually not sure what would be the correct fix for it. With my suggestion, you won't be able to override the type after the schema was built. I think the good fix requires a way to "freeze" types explicitly (and maybe freeze them automatically once the schema is built).

When frozen - it will simply return the `this._gqType` without mutations. But this sounds like a rather big change. We were able to do exactly this in a hacky way in this workaround in Gatsby: https://github.com/gatsbyjs/gatsby/pull/29822

But the fix for general case is probably more involved 😒

**Comment by nodkz** [comment]
@vladar made exactly what I suppose to do to fix this problem  👍👍👍

@KyleAMathews can you make profiling again from the gatsby master branch and provide new timings?
And if this change improves timings dramatically then I'll start to implement memoization for `getType()` method. Thanks!

**Comment by nodkz** [comment]
About asked questions and suggestions:

> How do you change the type? Are they immutable? Or have easily trackable ways of mutation? If so, we could just always return the cached version right?

Nope, types are not immutable. And it's a good feature request but a solution will be very complicated - need to track `fileds`, `args`  in fields, `extensions` & `deprecationReason` & `astNode` in args and fields and in type itself, `defaultValue` in args, `interfaces` in type. So it can be a nightmare in the code which provides a small worth. 

> Or have easily trackable ways of mutation? If so, we could just always return the cached version right?

For now, there are no trackable ways of mutation. Your issue is the first request in this field. So I'm very glad that we found this problem. But I'm sorry that this blind point brought inconvenience.  

> Or perhaps if it's not easy to tell when a type is mutated, perhaps we could manually "freeze" the types since we're controlling changing them.

Yep, we definitely should freeze types when calling `schemaComposer.buildSchema()`. BUT I want to keep type changing in runtime which unlocks the ability to extend & modify & swap graphql schema online without restarting the server. 

This feature will be highly demanded in [graphql-compose-modules](https://github.com/graphql-compose/graphql-compose-modules) in the future. BTW take some time to look at this new way of schema construction. I have been using it for more than a year and very happy with it. It uses directory structure for schema definition (like next.js uses files in the `pages/` folder). Moreover, this structure helps apply different middlewares on schema entrypoints.

> So maybe if we skip field generation if `this._fields` is `object`. EDIT: actually only 2 tests are failing with this change.

No. It's a bad idea for the following reasons:

- Hoisting problems. You definitely may get conditions when some types have references for each other and placed in different js modules and you will get undefined types for some fields. For solving this problem graphql-js uses code which you provided above - on the top level when you create a schema instance for the first run they deferred initialize all fieldConfigs from thunks (all js modules already initialized) and after that uses them without hoisting problem.
- `ObjectTypeComposer` contains it's own fieldConfig map. So if you call `getType()` and after that modify some field then this field will be changed in `ObjectTypeComposer._gqcFields` but not in generated `GraphQLObjectType`. The reason for having own fieldConfig 
  - 1) It keeps TypeComposers as type property and it saves time when you need to modify schemas via astVisitors. 
  - 2) Solves hoisting problem better that it allows `graphql-js` - you may get a list of fields while some types inside are not yet initialized. With graphql-js all fieldConfig map is thunked, but in graphql-compose just `type` property thunked for every field in map.

**Comment by KyleAMathews** [comment]
Profiled the same site again with @vladar's fix and time spent in graphql-compose dropped from 1578ms to 5ms 😆 so that's good change.

QPS went from 349 to 1527 so 4.4x speedup!

<img width="1133" alt="Screen Shot 2021-02-27 at 10 15 32 AM" src="https://user-images.githubusercontent.com/71047/109396397-301dc280-78e6-11eb-888f-c874768ca49a.png">

**Comment by nodkz** [comment]
Great news! 🎉

I'm curious. Do you create graphql schema for every request?

**Comment by nodkz** [comment]
I considered different scenarios how to fix this problem and chose the following plan:

1) Convert codebase on TypeScript. I want to get rid of Flowtype because it extremely slow and introducing new changes to the codebase brings a lot of pain. Also, Flowtype blocks to gather new contributors.
2) Construct `astNode` immediately on type change. Make changes focused, e.g., if arg updated, then change just its `astNode`. This will update GraphQL type immediately on any change and make `getType()` method cheap.
3) Remove directives from `extensions`. Directives will be stored in `astNode` only. This is my old mistake which was added when `astNode` didn't exist.
4) Bump 8.0.0 version. API should not be changed.

Sorry, but these changes may take several months. I am happy that @vladar's fix works fine for you. This gives me time to fix this problem properly and remove old hacky things.

@vladar, if you have any thoughts or additions, please tell me ;)

**Comment by vladar** [comment]
Hey @nodkz Thank you so much for your prompt replies 💜 

The plan sounds cool to me! I am not sure about extensions though - we use them interchangeably with directives. But I think we will figure something out. In general, separating the two makes sense to do (as for me).

**Comment by nodkz** [comment]
@vladar now all `TC.getType()` methods have memorization.

You may upgrade to v9.0.0 and remove the following hotfix https://github.com/gatsbyjs/gatsby/pull/29822

**Comment by vladar** [comment]
Great news, thanks! 🎉
