### ISSUE TITLE
Add a dependency for graphql

### ISSUE THREAD

**Issue by YizYah** [graphql-compose/graphql-compose#360]
I am wondering if perhaps you should include `graphql` as a proper dependency rather than just as a dev-dependency?  It seems to me that if I use your package I must independently include graphql.

I realize that in practice it may be a very uncommon use case not to have `graphql` included and to use `graphql-compose`.  But on principle it might be appropriate for you to export every package upon which you depend.

I accidentally found this problem when I included `@neo4j/graphql` as a dev-dependency for a test.  It was failing in CI:
```
  Error: Cannot find module 'graphql'

  Require stack:

  - /home/travis/build/YizYah/neo-forgery/node_modules/graphql-compose/lib/graphql.js

  - /home/travis/build/YizYah/neo-forgery/node_modules/graphql-compose/lib/index.js

  - /home/travis/build/YizYah/neo-forgery/node_modules/@neo4j/graphql/dist/index.js

  - /home/travis/build/YizYah/neo-forgery/test/custom/server.test.ts

  - /home/travis/build/YizYah/neo-forgery/node_modules/ava/lib/worker/subprocess.js

  › - node_modules/ava/lib/worker/subprocess.js

  › Object.<anonymous> (node_modules/graphql-compose/src/graphql.ts:1:1)
  ```

**Comment by nodkz** [comment]
@YizYah `graphql` is listed as peerDependency and must be required independently and explicitly.

`graphql` package is used in many other libraries and there it also is listed as peerDependecy. Why that? 
- Because `graphql` has global classes and if one package imports graphql@15.0.0 and another graphql@15.0.1 then references to these classes will be different. And in runtime your code fails because internally it has `instanceof` checks.
- Moreover, graphql-compose has backward compatibility with graphql@14. So the developer chooses what GraphQL specification implementation in runtime he wants to use.

So better to not include `graphql` as a package.json dependency in `graphql-compose`. It's really better to do in your app code. You will have more control.
